#!/usr/bin/env bash
# Fetch guest NATS creds from SSM and write them to a .env file consumed by
# `cargo build` so they get baked into the desktop binary via option_env!.
#
# Run this once before building the desktop app (CI, local dev, release).
# See vettid-dev/docs/DESKTOP-CONNECTION-FLOW.md for why these are public.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.cargo-env"

# Allow overriding the SSM parameter paths in case you're pointing at a
# non-prod account. Defaults match vettid-dev/cdk/scripts/init-nats-operator.ts.
JWT_PARAM="${VETTID_GUEST_JWT_PARAM:-/vettid/nats/guest-user-jwt}"
SEED_PARAM="${VETTID_GUEST_SEED_PARAM:-/vettid/nats/guest-user-seed}"
NATS_URL="${VETTID_NATS_URL:-tls://nats.vettid.dev:443}"

command -v aws >/dev/null 2>&1 || {
    echo "error: aws CLI not found — install it or set creds manually" >&2
    exit 1
}

echo "Fetching guest creds from SSM ($JWT_PARAM, $SEED_PARAM)…"
JWT="$(aws ssm get-parameter --name "$JWT_PARAM" --with-decryption --query Parameter.Value --output text)"
SEED="$(aws ssm get-parameter --name "$SEED_PARAM" --with-decryption --query Parameter.Value --output text)"

if [[ -z "$JWT" || "$JWT" == "None" || -z "$SEED" || "$SEED" == "None" ]]; then
    echo "error: SSM returned empty JWT or seed — is the guest account provisioned?" >&2
    exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/fetch-guest-creds.sh — do NOT edit by hand.
# These are compile-time values baked into the desktop binary via option_env!.
# Source this file before running cargo/tauri commands:
#     set -a && source $ENV_FILE && set +a
VETTID_GUEST_JWT='$JWT'
VETTID_GUEST_SEED='$SEED'
VETTID_NATS_URL='$NATS_URL'
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"
echo ""
echo "To use in your current shell:"
echo "    set -a && source $ENV_FILE && set +a"
echo ""
echo "Then run: npm run build && cargo tauri build"
